// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace ExampleWebClient.Models
{
    public partial class UserProfile
    {
        private string _contactInfo;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string ContactInfo
        {
            get { return this._contactInfo; }
            set { this._contactInfo = value; }
        }
        
        private int? _id;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? Id
        {
            get { return this._id; }
            set { this._id = value; }
        }
        
        private string _manager;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Manager
        {
            get { return this._manager; }
            set { this._manager = value; }
        }
        
        private string _name;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Name
        {
            get { return this._name; }
            set { this._name = value; }
        }
        
        private string _photo;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Photo
        {
            get { return this._photo; }
            set { this._photo = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the UserProfile class.
        /// </summary>
        public UserProfile()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken contactInfoValue = inputObject["ContactInfo"];
                if (contactInfoValue != null && contactInfoValue.Type != JTokenType.Null)
                {
                    this.ContactInfo = ((string)contactInfoValue);
                }
                JToken idValue = inputObject["Id"];
                if (idValue != null && idValue.Type != JTokenType.Null)
                {
                    this.Id = ((int)idValue);
                }
                JToken managerValue = inputObject["Manager"];
                if (managerValue != null && managerValue.Type != JTokenType.Null)
                {
                    this.Manager = ((string)managerValue);
                }
                JToken nameValue = inputObject["Name"];
                if (nameValue != null && nameValue.Type != JTokenType.Null)
                {
                    this.Name = ((string)nameValue);
                }
                JToken photoValue = inputObject["Photo"];
                if (photoValue != null && photoValue.Type != JTokenType.Null)
                {
                    this.Photo = ((string)photoValue);
                }
            }
        }
    }
}
